### PR TITLE
add _meta.apiVersion to pythonPackages

### PR DESCRIPTION
**Pull request by DavHau**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Thank you, but I prefer not to put it in the package set. The set may have an interface as well, but it is different from that of the build functions. Thus, adding it to the builder may make more sense, but then of course you cannot introspect it beforehand. I don't know when exactly you want to know the version. 

We could add it here, but then it needs to become clear that the version reflects the api of `buildPython*`.

**Comment by DavHau** [comment]
When dealing with packages in an autoamtic fashion, I have 2 different scenarios in mind:
1. overriding existing packages
2. creating packages from scratch

For (1.) it would be best to have the api version in the passthru argument of a package
For (2.) it would be good to be able to inspect the buildPythonPackage version before calling it.

Since the package set is already in the passthru of each packge (via `{package}.pythonModule.pkgs`), adding the information to the package set would solve both cases.

What do you think about: `python.pkgs._meta.version.buildPythonPackage = 1`

**Comment by FRidh** [comment]
cc @jonringer

**Comment by FRidh** [comment]
@DavHau could you move this PR to `nixpkgs` repo and target `master` instead. We can solve this issue before merging https://github.com/NixOS/nixpkgs/pull/102613.

**Comment by DavHau** [comment]
Sure, will do tomorrow.

**Comment by jonringer** [comment]
Another option would be to expose another mkDerivation wrapper, (e.g. `buildPythonModule`), that can be more "strict" about python packages being added to `propagatedBuildInputs`, and have people transition to it.

This is painful in many regards, but fundamentally changing how an ecosystem works in nixpkgs should be painful, as many people downstream will incur pain.

And I think only a handful or two of people are aware of these changes, it would be nice to have more people involved as to shed light on potential edge cases, and unintended breakages.

I guess I just don't like breaking changes, and I would prefer never to experience this again. We should be very confident that this will be the "desired end-state" for all python packaging in nixpkgs before going forward with these changes.

**Pull request closed without merging**
